sudo: required
dist: bionic
language: generic
services:
- mysql
jobs:
  include:
  - stage: build, test, and deploy
    if: tag IS blank
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y golang-go
    - go version
    - export GOPATH=$PWD
    - mysql -u root < setup.sql
    install:
    - go get "github.com/go-sql-driver/mysql"
    - go get "github.com/sparrc/go-ping"
    - go get "gopkg.in/yaml.v2"
    - bash -x travis/go-build.sh
    script:
    - ls -lrt builds/
    - sudo ./builds/pingnstor-linux-amd64 -dsn "root@tcp(localhost)/pingnstor" -f
      config.yml  &
    - sleep 120
    - sudo killall pingnstor-linux-amd64
    - bash -x travis/go-test.sh
    deploy:
      provider: releases
      api_key:
        secure: X4DtEu8M+MJIwsGKkoeKF1aAKfSO7xB3QUOlsRJTq5AuMGq7Hew+2hoXq/xk6xC3b4yCF6rd8cBCkdNFV3phsTLaC4Qe3I83HOb7Nq13WcmGgsaC15s4EnQIG+5zwLbgNvzOfgTfaf/2kw2/SIfM3wekOLti7UfjC+k/Fdqco8gXJ3f7d97eG+//3DTp/noL+Mq2cCEgIgcLdpJEhZlzE8SZfpZIQwlo1l95QfMRYKlfJHymOsariSh8Zq2x+CZctSRDg4P9dUPIzgSFW2Grp6QUimU0rJ4TG1Rk3b8+j7KxyW5WPSU/ONRJNBQr+/czT/WuIsSTUi4t5g2IYx/WazZpqp2VF0iyBhQEQpdXlYAt6dwBA8nranJbvsj2svKWhgeFezA3ZjPZcY7SnPMQJtNm4z70pass19ayvliEeHinNrlycfstuCB5AsB8ZgehZwFYf0ao+4DiIgLj1tGUbmGFN2V8d0YDcksHzH7WXnyO/QIJOApsZrlIKqhSWwH4F8tyk8JnQi5+zwLByhdyTezEr3KVPnlFKi14hFNLaY+fhjPOHdKmYcOmc7RWF/gzT1UJGgl8jInGH/tlBDksaKrlGZA7l+N+QR333X7M2OmMGSkwlkvVstagxJeIbmZEJfYgEeM9ISqbM13SRokaI/G3r7QhZKWkWsgMD/tHMQA=
      file_glob: true
      file: builds/*
      skip_cleanup: true
      draft: true
      on:
        branch: master
        repo: jrcichra/pingnstor
env:
  global:
  - secure: jhoz9XmeEOhpboratQBJE0AnzhAlSW6YjR+F1z2jjUXBnO0zZFAf8LMQlYkZHMQMUygeQgyYOS8i+xKelrlhTVVHOqVUdPTxkFtKpTozKsumF2TVHtxdNiGaFM+VVGwM53wjCj6i4hIErxp2oRJW8aIBynJ3MBpVetGKPJB0mAcBfOntJisANsFtK4AuAn6klX+5tY7vOzXriU0S6guuLqCKtDg/Z4SFkx1tWJIhkPVuxIpFXF2taIXoxmShlS0Di3QWUkJgPMXETWp/BWM6kKyalXNA7+lss/9ytDpZFD0WVsHr9GPB1TADX+OMHr/k7/KCWJmNA5jAttg72fjfaeYGCZBQmRkWI0gy3MwQ1EMofm65n1SU/si8ikFnsyNLJwEOmKh5XFMQb+a/9Zq3wNj7/jYb+J/0yjGDsxUKNrKhsx3Pt+mY2wmCD9TvHWvZs0stiY+hGcXCVPgEF6tjceRJUDwxT0AqILVdrup9z0BKq948HUrovKZbmZEgvCKgH0WNR/HYiqflNrODNl7niIMkgXa4R//6SGkEdMz4D7ccS8RjTr/A3srCYk+VVyzZYLXZgOqHX08oKxyyKxPgU/Uu5svupcWh2Yl0a5lV8qRNAXE1jElHD0QKcXKtESUJmxC11i6DSU38kFWfrRnqxL3I27VfbMNrgDSuFQuU8gA=
  - secure: BIcL/VouUe1C8AuuZLFXdEVvELpSGGkq3pj1GrIEuOm5tgwv8ZAtizrHaMEHdMFcOWwuDzbvYyY4INfl8nhLq9uAwx1LuIwmGa91AMavtCf3ROpZ/FEkH0glHRQjGkq4oyHqNdTkpv/qx3aKA49PHZ7yfgDWivwqmKi33YNsihlkCku5ZheMpAcrCf/nw3K0+cHmTbKMT8GYBx4RM1aEruEobS5j54FVW+m7TpYEst5aKNdqKwExVHUA9tLIYFhJoOFpR1F3dWDm4p3S1KrOmvcwTuTSy3HY0zHdXOO3aXMbO7Mf+DmetUni18MLtN9oEReTS/YDhEfyBa9cB4EbPk3Is7iRPCUUs2NbEZuBELkX2c+8a7KVV9kPgkzXidQYtLImvrra3lQXuVPd1WahXAyAr9RzGM4QYdrxzNehN7IVo/fyWpvu0RwuY7GDOIAkVu+qzHC+xYnpRo5XFtqZ8OzrVGiS2hVp79unmpI0pGordgq2josBS6Bq2XgahPVnQa7ME0vs7eUrEls5hCkMl2oYtE2eLo3QJzu2Hc0Eq6SGLXrOa9nQ/2heCuiHRc1yYZxK6fDSNz81VAWId4hYeRQTAMAdDhOBD6EHUHc8rwPPZyWm4R+F9DhcFNqR45PIt218lTmDo8ba+oG/8SQ3O7oJ6Yhk82/KxpUQZZ177Dg=