name: pingnstor
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install and prepare MariaDB
        run: |
          sudo apt install -y software-properties-common
          sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
          sudo add-apt-repository "deb [arch=amd64,arm64,ppc64el] http://mariadb.mirror.liquidtelecom.com/repo/10.4/ubuntu $(lsb_release -cs) main"
          sudo apt update && sudo apt -y install mariadb-server
          mysql -u root -proot < setup.sql
      - name: Get dependencies
        run: |
          go get "github.com/go-sql-driver/mysql"
          go get "github.com/sparrc/go-ping"
          go get "gopkg.in/yaml.v2"
      - name: Build
        run: |
          bash -x actions/go-build.sh
      - name: Build Containers
        run: |
          bash -x actions/docker.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Test
        run: |
          ls -lrt builds/
          sudo ./builds/pingnstor-linux-amd64 -dsn "root:root@tcp(localhost)/pingnstor" -f config.yml  &
          sleep 120
          sudo killall pingnstor-linux-amd64
          bash -x actions/go-test.sh
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "builds/*"
          draft: "true"
          tag: "asdf"
          token: ${{ secrets.GITHUB_TOKEN }}
