name: pingnstor
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up DB
        run: |
          mysql -u root -proot < setup.sql
      - name: Get dependencies
        run: |
          go get "github.com/go-sql-driver/mysql"
          go get "github.com/sparrc/go-ping"
          go get "gopkg.in/yaml.v2"
      - name: Build
        run: |
          bash -x actions/go-build.sh
      - name: Test
        run: |
          ls -lrt builds/
          sudo ./builds/pingnstor-linux-amd64 -dsn "root:root@tcp(localhost)/pingnstor" -f config.yml  &
          sleep 120
          sudo killall pingnstor-linux-amd64
          bash -x actions/go-test.sh
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            builds/pingnstor-windows-amd64.exe
            builds/pingnstor-windows-386.exe
            builds/pingnstor-linux-amd64
            builds/pingnstor-linux-arm 
            builds/pingnstor-linux-arm64
          draft: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
